const GRAPH_ORDER_PATTERNS = [
  /\b(?:(?:dependenc(?:y|ies)|prerequisites?)[-\s]+(?:dag|graph|order(?:ing)?|relation(?:ship)?s?|direction|edges?|chains?)|(?:topological(?:ly)?\s+(?:sort(?:ed|ing)?|order(?:ed|ing)?)|dag(?:\s+(?:order(?:ing)?|edges?|schedule))?)|first[-\s]+(?:observed|seen|encountered)[-\s]+order|replay order|deduplicat(?:e|ion)[^.!?\n]{0,48}\border|before (?:its|their|the) dependents?)\b/i,
  /\b(?:preserve|maintain|follow|respect|use)\b[^.!?\n]{0,24}\b(?:stable (?:input )?order|input order|stable order)\b[^.!?\n]{0,48}\b(?:schedul(?:e|ed|ing)|jobs?|tasks?|nodes?|steps?|dependents?|dependenc(?:y|ies)|prerequisites?|ranks?|ranked|priorit(?:y|ies)|ties?|tie[-\s]?break)\b|\b(?:schedul(?:e|ed|ing)|emit(?:s|ted|ting)?|process(?:es|ed|ing)?|ranks?|ranked|priorit(?:y|ies)|ties?|tie[-\s]?break)\b[^.!?\n]{0,48}\b(?:jobs?|tasks?|nodes?|steps?|dependents?)?[^.!?\n]{0,32}\b(?:stable (?:input )?order|input order|stable order)\b/i,
  /\b(?:dependenc(?:y|ies)|prerequisites?|dag|graph|scheduler|jobs?|tasks?|nodes?)\b[^.!?\n]{0,64}\b(?:acyclic|cyclic|cycle detection|(?:detect|reject|prevent|avoid|report|forbid|form|contain|create)(?:s|ed|ing)?\s+cycles?)\b|\b(?:acyclic|cyclic|cycle detection|(?:detect|reject|prevent|avoid|report|forbid|form|contain|create)(?:s|ed|ing)?\s+cycles?|cycles?\s+(?:in|among|through))\b[^.!?\n]{0,64}\b(?:dependenc(?:y|ies)|prerequisites?|dag|graph|scheduler|jobs?|tasks?|nodes?)\b/i,
  /\b(?:run|execute|start|schedule|process|emit|appear)\b[^.!?\n]{0,48}\bafter\b[^.!?\n]{0,48}\b(?:(?:all|each|every|its|their|the)\s+)?(?:dependenc(?:y|ies)|prerequisites?)\s+(?:(?:must|should|shall|has|have|had)\s+)?(?:complete[sd]?|finish(?:ed|es)?|resolve[sd]?|ran|executed)\b/i,
  /\b(?:run|execute|start|schedule|process|emit|begin|appear)\b[^.!?\n]{0,48}\b(?:only\s+)?(?:once|when)\b[^.!?\n]{0,48}\b(?:all|each|every|its|their|the)?\s*(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,32}\b(?:complete[sd]?|finish(?:ed|es)?|resolve[sd]?|ran|executed)\b/i,
  /\b(?:run|execute|start|schedule|process|emit|begin|appear)\b[^.!?\n]{0,48}\buntil\b[^.!?\n]{0,48}\b(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,32}\b(?:complete[sd]?|finish(?:ed|es)?|resolve[sd]?|ran|executed)\b/i,
  /\b(?:jobs?|tasks?|nodes?|steps?|dependents?)\b[^.!?\n]{0,48}\bwait(?:s|ed|ing)?\s+for\b[^.!?\n]{0,32}\b(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,32}\b(?:complete|finish|resolve)\b/i,
  /\bwait\s+for\b[^.!?\n]{0,32}\b(?:(?:all|each|every|its|their|the)\s+)?(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,32}\bbefore\b[^.!?\n]{0,32}\b(?:run|running|execute|executing|start|starting|schedule|scheduling|process|processing|emit|emitting)\b[^.!?\n]{0,32}\b(?:jobs?|tasks?|nodes?|steps?|dependents?)\b/i,
  /\b(?:(?:each|every|all|the)\s+)?(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,48}\b(?:complete|finish|resolve)(?:s|d|ed)?\b[^.!?\n]{0,24}\b(?:before|prior\s+to)\b[^.!?\n]{0,24}\b(?:(?:run|running|execute|executing|start|starting|schedule|scheduling|process|processing|emit|emitting)\s+)?(?:the\s+)?(?:(?:dependent\s+)?(?:job|task|node|step)s?|dependents?)\b/i,
  /\b(?:jobs?|tasks?|nodes?|steps?|dependents?)\b[^.!?\n]{0,32}\b(?:eligible|ready)\b[^.!?\n]{0,24}\b(?:when|once)\b[^.!?\n]{0,32}\b(?:each|every|all|the|its|their)?\s*(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,24}\b(?:is|are|be|become(?:s)?|remain(?:s)?)?\s*(?:done|complete[sd]?|finish(?:ed|es)?|resolve[sd]?)\b/i,
  /\b(?:run|execute|process|resolve|complete|schedule)\s+(?:each|every|all|the)\s+(?:dependenc(?:y|ies)|prerequisites?)\s+first\b/i,
  /\b(?:(?:each|every|all|the)\s+)?(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,48}\b(?:precede(?:s)?|come(?:s)?\s+before|run(?:s)?\s+before|execute(?:s)?\s+before|finish(?:es)?\s+before|complete(?:s|d)?\s+before)\b[^.!?\n]{0,32}\b(?:the\s+)?(?:(?:dependent\s+)?(?:job|task|node|step)s?|dependents?)\b/i,
  /\bdepends?\s+on\b[^.!?\n]{0,64}\b(?:run|runs|ran|execute|executes|executed|start|starts|started|schedule|schedules|scheduled|process|processes|processed|emit|emits|emitted)\b[^.!?\n]{0,24}\b(?:after|afterward|afterwards|later)\b/i,
  /\bdepends?\s+on\b[^.!?\n]{0,64}\b(?:run|execute|start|schedule|process|emit)(?:s|d|ed|ing)?\b[^.!?\n]{0,24}\b[^.!?\n]{0,24}\bfirst\b/i,
  /\b(?:run|execute|start|schedule|process|emit)(?:s|d|ed|ing)?\b[^.!?\n]{0,32}\b(?:dependenc(?:y|ies)|prerequisites?)\b[^.!?\n]{0,24}\bfollowed\s+by\b[^.!?\n]{0,24}\b(?:(?:the\s+)?dependent|(?:the\s+)?(?:job|task|node|step)s?)\b/i,
  /\b(?:run|execute|start|schedule|process|emit)(?:s|d|ed|ing)?\b[^.!?\n]{0,48}\bbefore\b[^.!?\n]{0,48}\bdepends?\s+on\b/i,
  /\b(?:do\s+not|don't|never)\s+(?:run|execute|start|schedule|process|emit|begin)\b[^.!?\n]{0,48}\b(?:jobs?|tasks?|nodes?|steps?|dependents?)\b[^.!?\n]{0,48}\bbefore\b[^.!?\n]{0,32}\b(?:dependenc(?:y|ies)|prerequisites?)\b/i
];

export function hasGraphOrderContract(request: string): boolean {
  return GRAPH_ORDER_PATTERNS.some((pattern) => pattern.test(request));
}
